#!/usr/bin/env python3
"""
agent-life Workspace Coverage Walkthrough (WP3 — `alf add`)
==========================================================

Teaches the explicit "track arbitrary workspace files" feature: how an agent
opts a file into sync with `alf add` (ALF never auto-walks/slurps a workspace),
where the whitelist + removal log live (`.alf-include.json` / `.alf-sync-log.md`,
both synced so they travel on restore), and how changes propagate.

Because arbitrary files are opaque bytes the delta format can't carry, a change
to a tracked file makes `alf sync` upload a fresh **snapshot** (a clean,
non-destructive rollover) instead of a delta — while memory-only changes still
ride efficient deltas. Deleting a tracked file prunes it from the whitelist and
appends a note to `.alf-sync-log.md`.

The CLI lifecycle steps drive the REAL `alf` binary against the live service and
verify each effect in Neon + S3. They skip cleanly if `alf` is not available.

Follows the same UX as `integration_walkthrough.py` (banner, steps, pauses,
markdown report).

Prerequisites:
  pip install requests psycopg2-binary boto3 python-dotenv
  A built `alf` on PATH or under target/ (for the CLI lifecycle steps).

Environment (.env or exported): same as integration_walkthrough.py
  API_BASE_URL, API_KEY, NEON_DATABASE_URL, S3_BUCKET_NAME, AWS_REGION

Usage:
  python3 integration_walkthrough_for_workspace.py
  python3 integration_walkthrough_for_workspace.py --no-pause
  python3 integration_walkthrough_for_workspace.py --report workspace_report.md
"""

from __future__ import annotations

import argparse
import io
import json
import os
import subprocess
import sys
import tempfile
import uuid
import zipfile
from pathlib import Path
from typing import Optional

# Reuse clients, UI, connectivity, and report types from the main walkthrough.
_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

import integration_walkthrough as iw

# ---------------------------------------------------------------------------
# Workspace-coverage agent (must not collide with the other walkthroughs)
# ---------------------------------------------------------------------------

WS_AGENT_ID = uuid.UUID("e2e10000-feed-4000-b000-000000000003")
WS_AGENT_NAME = "E2E Workspace Walkthrough Agent"

INCLUDE_FILE = ".alf-include.json"
SYNC_LOG_FILE = ".alf-sync-log.md"


def _adapt_report_markdown(md: str) -> str:
    return md.replace(
        "agent-life Integration Test Report",
        "agent-life Workspace Coverage Walkthrough Report",
    ).replace(
        "*Generated by `integration_walkthrough.py`*",
        "*Generated by `integration_walkthrough_for_workspace.py`*",
    )


# ---------------------------------------------------------------------------
# CLI lifecycle helpers
# ---------------------------------------------------------------------------


def _alf_env(home: Path) -> dict:
    """A child-process environment with HOME redirected to an isolated dir, so
    the CLI's ~/.alf (config + state + base snapshot) never touches the host."""
    env = dict(os.environ)
    env["HOME"] = str(home)
    env.pop("ALF_HUMAN", None)  # force JSON stdout
    return env


def _write_alf_config(home: Path, cfg: iw.Config) -> None:
    alf_dir = home / ".alf"
    alf_dir.mkdir(parents=True, exist_ok=True)
    (alf_dir / "config.toml").write_text(
        f'[service]\napi_url = "{cfg.api_url}"\napi_key = "{cfg.api_key}"\n\n'
        f'[defaults]\nruntime = "openclaw"\n',
        encoding="utf-8",
    )


def _run_alf(alf: str, home: Path, args: list[str]) -> tuple[subprocess.CompletedProcess, Optional[dict]]:
    proc = subprocess.run(
        [alf, *args],
        capture_output=True,
        text=True,
        env=_alf_env(home),
        timeout=180,
    )
    parsed: Optional[dict] = None
    if proc.stdout.strip():
        try:
            parsed = json.loads(proc.stdout.strip())
        except json.JSONDecodeError:
            parsed = None
    return proc, parsed


def _seed_workspace(ws: Path) -> None:
    (ws / "memory").mkdir(parents=True, exist_ok=True)
    (ws / "SOUL.md").write_text(f"# {WS_AGENT_NAME}\n\nA tidy agent.\n", encoding="utf-8")
    (ws / "MEMORY.md").write_text("## Facts\n\nThe sky is blue.\n", encoding="utf-8")
    (ws / "memory" / "2026-02-01.md").write_text("## Log\n\nStarted up.\n", encoding="utf-8")
    # A pre-existing fixed agent id so DB queries + cleanup target a known UUID.
    (ws / ".alf-agent-id").write_text(str(WS_AGENT_ID) + "\n", encoding="utf-8")


# alf-managed files worth calling out in the tree so the reader notices them.
_TREE_NOTES = {
    INCLUDE_FILE: "tracked-file whitelist (synced)",
    SYNC_LOG_FILE: "removal log (synced, agent-readable)",
    ".alf-agent-id": "stable agent id",
}


def _print_tree(root: Path, title: str) -> None:
    """Render the workspace as an indented tree, flagging alf-managed files, so
    the reader can watch the workspace evolve across the lifecycle."""
    print(f"  {iw.c('yellow', title)}")
    print(f"    {root.name}/")

    def walk(directory: Path, prefix: str) -> None:
        # Directories first, then files; alphabetical within each — the usual
        # `tree` ordering, and deterministic for a reproducible walkthrough.
        children = sorted(directory.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
        for i, child in enumerate(children):
            last = i == len(children) - 1
            connector = "└── " if last else "├── "
            if child.is_dir():
                print(f"    {prefix}{connector}{child.name}/")
                walk(child, prefix + ("    " if last else "│   "))
            else:
                rel = child.relative_to(root).as_posix()
                note = _TREE_NOTES.get(rel, "")
                suffix = f"  {iw.c('dim', '← ' + note)}" if note else ""
                size = child.stat().st_size
                print(f"    {prefix}{connector}{child.name} {iw.c('dim', f'({size} B)')}{suffix}")

    walk(root, "")
    print()


def _snapshot_count(db: iw.DbClient) -> int:
    row = db.query_one(
        "SELECT count(*) AS n FROM snapshots WHERE agent_id = %s", (str(WS_AGENT_ID),)
    )
    return int(row["n"]) if row else 0


def _delta_count(db: iw.DbClient) -> int:
    row = db.query_one(
        "SELECT count(*) AS n FROM deltas WHERE agent_id = %s", (str(WS_AGENT_ID),)
    )
    return int(row["n"]) if row else 0


def _latest_snapshot_blob(db: iw.DbClient) -> Optional[str]:
    row = db.query_one(
        "SELECT blob_key FROM snapshots WHERE agent_id = %s "
        "ORDER BY sequence DESC, created_at DESC LIMIT 1",
        (str(WS_AGENT_ID),),
    )
    return row["blob_key"] if row else None


def _raw_names_in_blob(s3: iw.S3Client, blob_key: str) -> list[str]:
    obj = s3.s3.get_object(Bucket=s3.bucket, Key=blob_key)
    raw = obj["Body"].read()
    zf = zipfile.ZipFile(io.BytesIO(raw))
    return [n for n in zf.namelist() if n.startswith("raw/openclaw/")]


# ---------------------------------------------------------------------------
# Concept steps
# ---------------------------------------------------------------------------


def step_concept_opt_in(cfg: iw.Config, report: iw.Report):
    iw.section(1, "Explicit Opt-In (Concept) — `alf add`, not auto-walk")
    iw.explain(
        """
        ALF deliberately does NOT scan a workspace and slurp every file. The
        agent opts each arbitrary file into sync explicitly:

            alf add notes.txt -r openclaw -w <workspace>

        Known files (SOUL.md, IDENTITY.md, memory/…) are always covered. `alf add`
        extends coverage to anything else the agent wants backed up — a report it
        wrote, a CSV it maintains — without the risk of accidentally syncing a
        50 GB dataset or a node_modules tree.

        Two small files in the workspace carry the state, and both are themselves
        synced so they travel on restore:

          • .alf-include.json  — the whitelist/inventory of opted-in files.
          • .alf-sync-log.md   — an append-only log of removals, so the agent can
                                  later answer "what happened to notes.txt?".
        """
    )
    report.add(iw.StepResult("Opt-in model (concept)", True, 0, "alf add vs auto-walk"))
    iw.pause(cfg)


def step_concept_propagation(cfg: iw.Config, report: iw.Report):
    iw.section(2, "How Tracked Changes Propagate (Concept) — re-snapshot")
    iw.explain(
        """
        Memory records ride incremental DELTAS. Arbitrary tracked files are opaque
        bytes the delta format can't carry, so:

          • Change a tracked file (add / edit / delete) → the next `alf sync`
            uploads a fresh SNAPSHOT. The service treats this as a clean,
            non-destructive ROLLOVER: a new base at the current sequence; prior
            snapshots/deltas are retained for point-in-time restore.
          • Change only memory → the next `alf sync` still pushes an efficient
            DELTA.

        Deleting a tracked file is handled before export: `alf sync` prunes it from
        .alf-include.json and appends a note to .alf-sync-log.md, then re-snapshots
        (so the restored snapshot simply omits the file).
        """
    )
    report.add(iw.StepResult("Propagation (concept)", True, 0, "re-snapshot vs delta"))
    iw.pause(cfg)


# ---------------------------------------------------------------------------
# CLI lifecycle (drives the real `alf` binary against the live service)
# ---------------------------------------------------------------------------


def step_cli_lifecycle(
    cfg: iw.Config,
    api: iw.ApiClient,
    db: iw.DbClient,
    s3: iw.S3Client,
    report: iw.Report,
):
    iw.section(3, "End-to-End Lifecycle with the Real `alf` CLI")
    iw.explain(
        """
        We drive the actual `alf` binary against the live service, with HOME
        redirected to a temp dir (isolated config + state). Sequence:

          1. first  `alf sync`  → snapshot (registers the agent)
          2. `alf add report.md` + `alf sync` → RE-SNAPSHOT (tracked file added)
          3. edit MEMORY.md + `alf sync` → DELTA (memory-only change)
          4. delete report.md + `alf sync` → prune + log + RE-SNAPSHOT

        Each effect is verified in Neon (snapshot/delta rows) and S3 (the blob's
        raw/openclaw/ contents). Skips cleanly if `alf` is unavailable.
        """
    )

    alf = iw.find_alf_binary()
    if not alf:
        iw.ok("`alf` not found on PATH or in target/ — skipping the CLI lifecycle")
        report.add(iw.StepResult("CLI lifecycle", True, 0, "alf not available"))
        iw.pause(cfg)
        return
    print(f"  Using alf binary: {alf}")

    # Ensure a clean slate: remove any agent left by a prior run so the first
    # `alf sync` is a true first sync (HOME is fresh, so local state is empty).
    api.delete(f"/agents/{WS_AGENT_ID}")

    ok = True
    try:
        with tempfile.TemporaryDirectory() as home_s, tempfile.TemporaryDirectory() as ws_s:
            home = Path(home_s)
            ws = Path(ws_s) / "workspace"
            ws.mkdir(parents=True)
            _write_alf_config(home, cfg)
            _seed_workspace(ws)
            _print_tree(ws, "Workspace — seeded (before first sync)")

            sync_args = ["sync", "-r", "openclaw", "-w", str(ws)]

            # 1) First sync → snapshot.
            proc, res = _run_alf(alf, home, sync_args)
            if proc.returncode != 0 or not res:
                raise RuntimeError(
                    f"first sync failed: {(proc.stderr or proc.stdout)[:300]}"
                )
            iw.ok(f"first sync → sequence {res.get('sequence')}, delta={res.get('delta')}")
            assert res.get("delta") is False, "first sync must be a snapshot"
            assert _snapshot_count(db) == 1, "expected exactly one snapshot after first sync"
            iw.ok(f"Neon: {_snapshot_count(db)} snapshot, {_delta_count(db)} deltas")
            _print_tree(ws, "Workspace — after first sync (unchanged; .alf-agent-id present)")

            # 2) alf add + sync → re-snapshot.
            (ws / "report.md").write_text("# Q1 Report\n\nNumbers go up.\n", encoding="utf-8")
            proc, res = _run_alf(alf, home, ["add", "report.md", "-r", "openclaw", "-w", str(ws)])
            if proc.returncode != 0:
                raise RuntimeError(f"alf add failed: {(proc.stderr or proc.stdout)[:300]}")
            iw.ok("alf add report.md")
            include = json.loads((ws / INCLUDE_FILE).read_text())
            print(f"    {INCLUDE_FILE}: {[f['path'] for f in include['files']]}")
            _print_tree(ws, "Workspace — after `alf add report.md` (report.md + include list)")

            proc, res = _run_alf(alf, home, sync_args)
            if proc.returncode != 0 or not res:
                raise RuntimeError(f"sync after add failed: {(proc.stderr or proc.stdout)[:300]}")
            assert res.get("delta") is False, "tracked-file add must re-snapshot, not delta"
            snaps = _snapshot_count(db)
            assert snaps == 2, f"expected a 2nd snapshot after add, got {snaps}"
            iw.ok(f"add → RE-SNAPSHOT (delta={res.get('delta')}); Neon now has {snaps} snapshots")

            blob = _latest_snapshot_blob(db)
            raw_names = _raw_names_in_blob(s3, blob) if blob else []
            assert "raw/openclaw/report.md" in raw_names, "report.md must be in the snapshot"
            assert f"raw/openclaw/{INCLUDE_FILE}" in raw_names, "include list must travel"
            iw.ok("S3: snapshot contains raw/openclaw/report.md and the include list")

            # 3) Memory-only change → delta.
            (ws / "MEMORY.md").write_text(
                "## Facts\n\nThe sky is blue.\n\n## More\n\nGrass is green.\n", encoding="utf-8"
            )
            proc, res = _run_alf(alf, home, sync_args)
            if proc.returncode != 0 or not res:
                raise RuntimeError(f"memory sync failed: {(proc.stderr or proc.stdout)[:300]}")
            assert res.get("delta") is True, "memory-only change must be a delta"
            deltas = _delta_count(db)
            assert deltas == 1, f"expected 1 delta after memory change, got {deltas}"
            iw.ok(
                f"memory-only → DELTA (delta={res.get('delta')}, seq {res.get('sequence')}); "
                f"Neon snapshots still {_snapshot_count(db)}, deltas {deltas}"
            )
            _print_tree(ws, "Workspace — after editing MEMORY.md (MEMORY.md grew; file set unchanged)")

            # 4) Delete tracked file → prune + log + re-snapshot.
            (ws / "report.md").unlink()
            proc, res = _run_alf(alf, home, sync_args)
            if proc.returncode != 0 or not res:
                raise RuntimeError(f"delete sync failed: {(proc.stderr or proc.stdout)[:300]}")
            assert res.get("delta") is False, "removing a tracked file must re-snapshot"
            snaps = _snapshot_count(db)
            assert snaps == 3, f"expected a 3rd snapshot after delete, got {snaps}"
            iw.ok(f"delete → prune + RE-SNAPSHOT; Neon now has {snaps} snapshots")

            include = json.loads((ws / INCLUDE_FILE).read_text())
            assert all(f["path"] != "report.md" for f in include["files"]), "report.md must be pruned"
            iw.ok(f"{INCLUDE_FILE} pruned: report.md no longer tracked")

            log = (ws / SYNC_LOG_FILE).read_text()
            assert "report.md" in log and "removed" in log, "removal must be logged"
            print(f"  {iw.c('yellow', SYNC_LOG_FILE)}:")
            print("    " + "\n    ".join(log.strip().splitlines()))

            blob = _latest_snapshot_blob(db)
            raw_names = _raw_names_in_blob(s3, blob) if blob else []
            assert "raw/openclaw/report.md" not in raw_names, "deleted file must be absent from snapshot"
            iw.ok("S3: latest snapshot no longer contains report.md (restore would omit it)")
            _print_tree(ws, "Workspace — after deleting report.md + sync (pruned; .alf-sync-log.md added)")

    except (RuntimeError, AssertionError, KeyError, json.JSONDecodeError) as e:
        ok = False
        iw.fail(str(e))

    report.add(
        iw.StepResult(
            "CLI lifecycle",
            ok,
            0,
            "add→re-snapshot, memory→delta, delete→prune+log+re-snapshot" if ok else "",
            "" if ok else "see output above",
        )
    )
    iw.pause(cfg)


def step_cleanup(cfg: iw.Config, api: iw.ApiClient, db: iw.DbClient, s3: iw.S3Client, report: iw.Report):
    iw.section(4, "Cleanup — Delete Workspace Walkthrough Agent")
    iw.explain(
        """
        `DELETE /agents/:id` removes the agent, cascades snapshot/delta rows, and
        deletes objects under `{tenant_id}/{agent_id}/` in S3.
        """
    )
    agent_row = db.query_one("SELECT tenant_id FROM agents WHERE id = %s", (str(WS_AGENT_ID),))
    tenant_id = str(agent_row["tenant_id"]) if agent_row else None
    s3_prefix = f"{tenant_id}/{WS_AGENT_ID}/" if tenant_id else None

    r = api.delete(f"/agents/{WS_AGENT_ID}")
    if r.status_code == 200:
        iw.ok(f"Agent deleted (HTTP 200) — {r.json().get('objects_removed', '?')} S3 objects removed")
    elif r.status_code == 404:
        iw.ok("Agent already absent (HTTP 404)")
    else:
        iw.fail(f"Delete failed (HTTP {r.status_code}): {r.text[:200]}")
        report.add(iw.StepResult("Cleanup", False, 0, error=r.text[:200]))
        iw.pause(cfg)
        return

    if s3_prefix:
        remaining = s3.list_objects(s3_prefix)
        if remaining:
            iw.fail(f"S3 still has {len(remaining)} objects under {s3_prefix}")
        else:
            iw.ok("S3 prefix is empty — all blobs removed")

    report.add(iw.StepResult("Cleanup", True, 0, "Removed agent + blobs"))
    iw.pause(cfg)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--no-pause", action="store_true", help="Run without interactive pauses (for CI)")
    parser.add_argument(
        "--report",
        type=str,
        default="integration_workspace_report.md",
        help="Output path for the markdown report",
    )
    args = parser.parse_args()

    cfg = iw.Config.from_env(interactive=not args.no_pause)
    api = iw.ApiClient(cfg)
    db = iw.DbClient(cfg)
    s3 = iw.S3Client(cfg)

    report = iw.Report()
    db_host = cfg.db_url.split("@")[-1].split("/")[0] if "@" in cfg.db_url else "?"
    report.config_summary = {"api_url": cfg.api_url, "s3_bucket": cfg.s3_bucket, "db_host": db_host}

    iw.banner("agent-life Workspace Coverage Walkthrough (WP3 — alf add)")
    print(f"  API:      {cfg.api_url}")
    print(f"  S3:       {cfg.s3_bucket}")
    print(f"  DB:       {db_host}")
    print(f"  Agent ID: {WS_AGENT_ID}")
    print(f"  Mode:     {'interactive' if cfg.interactive else 'batch'}")
    print()

    if cfg.interactive:
        print(iw.c("dim", "  Demonstrates `alf add` + tracked-file re-snapshot end to end."))
        print(iw.c("dim", "  Press Enter at each prompt to continue, or Ctrl-C to abort."))
        iw.pause(cfg, "Press Enter to begin...")

    try:
        iw.step_connectivity(cfg, api, db, s3, report)
        step_concept_opt_in(cfg, report)
        step_concept_propagation(cfg, report)
        step_cli_lifecycle(cfg, api, db, s3, report)
        step_cleanup(cfg, api, db, s3, report)
    except KeyboardInterrupt:
        print(f"\n\n  {iw.c('yellow', 'Interrupted by user.')}")
        print(f"  {iw.c('yellow', f'Agent {WS_AGENT_ID} may need manual cleanup.')}")
        report.add(iw.StepResult("Interrupted", False, 0, error="KeyboardInterrupt"))

    iw.banner("Report")
    md = _adapt_report_markdown(report.to_markdown())
    report_path = Path(args.report)
    report_path.write_text(md, encoding="utf-8")
    print(f"  Report written to: {report_path.resolve()}")
    print()

    passed = sum(1 for s in report.steps if s.passed)
    total = len(report.steps)
    total_ms = sum(s.duration_ms for s in report.steps)
    color = "green" if passed == total else "red"
    print(f"  {iw.c(color, f'{passed}/{total} steps passed')}  ({total_ms:.0f} ms total)")
    print()

    sys.exit(0 if passed == total else 1)


if __name__ == "__main__":
    main()
