#!/usr/bin/env python3
"""
agent-life Memory Types & Chunking Walkthrough (WP2 — source-handler table)
==========================================================================

Teaches how the OpenClaw adapter turns workspace Markdown into ALF memory
records: a declarative, path-aware *source-handler table* decides each file's
`memory_type`, `namespace`, and chunking strategy. Two strategies do the work:

  • OneRecordPerFile — the whole file is one record (procedures, curated docs,
    active-context). A procedure no longer shreds into one fragment per heading.
  • SplitByHeading   — one record per `## ` entry (daily journals, MEMORY.md).
    It is fence-aware (a `## ` inside a ``` block is NOT a split point) and
    drops empty-bodied sections — including a leading H1 date header, which used
    to surface as a useless standalone "Saturday, May 23rd, 2026" record.

Unlike the other walkthroughs this one needs NO service, .env, or cloud — memory
chunking is a purely local concern of the adapter. It builds a demo workspace,
runs the REAL `alf export` binary (HOME isolated), reads the resulting `.alf`,
and shows, per file, how many records came out, of what type, and contrasts that
with what the old structure-blind splitter would have produced.

Prerequisites:
  A built `alf` on PATH or under target/{debug,release}/. Nothing else.

Usage:
  python3 integration_walkthrough_for_memory.py
  python3 integration_walkthrough_for_memory.py --no-pause
  python3 integration_walkthrough_for_memory.py --report memory_report.md
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
import zipfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# UI (self-contained — mirrors integration_walkthrough.py's look, no deps)
# ---------------------------------------------------------------------------

COLORS = {
    "reset": "\033[0m", "bold": "\033[1m", "dim": "\033[2m", "green": "\033[32m",
    "yellow": "\033[33m", "blue": "\033[34m", "cyan": "\033[36m", "red": "\033[31m",
}


def c(color: str, text: str) -> str:
    return f"{COLORS.get(color, '')}{text}{COLORS['reset']}"


def banner(text: str) -> None:
    print("\n" + c("cyan", "═" * 74))
    print(c("cyan", f"  {text}"))
    print(c("cyan", "═" * 74) + "\n")


def section(num: int, title: str) -> None:
    print("\n" + c("bold", f"── Step {num}: {title} ──") + "\n")


def explain(text: str) -> None:
    for line in textwrap.dedent(text).strip().splitlines():
        print(c("dim", f"  │ {line}"))
    print()


def ok(msg: str) -> None:
    print(f"  {c('green', '✓')} {msg}")


def fail(msg: str) -> None:
    print(f"  {c('red', '✗')} {msg}")


def pause(interactive: bool, prompt: str = "Press Enter to continue...") -> None:
    if interactive:
        input(f"\n  {c('blue', '▸')} {prompt}")
    print()


@dataclass
class StepResult:
    name: str
    passed: bool
    details: str = ""
    error: str = ""


@dataclass
class Report:
    started_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    steps: list[StepResult] = field(default_factory=list)

    def add(self, r: StepResult) -> None:
        self.steps.append(r)

    def to_markdown(self) -> str:
        passed = sum(1 for s in self.steps if s.passed)
        lines = [
            "# agent-life Memory Types & Chunking Walkthrough Report",
            "",
            f"**Date:** {self.started_at.strftime('%Y-%m-%d %H:%M:%S UTC')}  ",
            f"**Scope:** WP2 source-handler table (local `alf export`, no service)  ",
            "",
            "## Summary",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Steps passed | {passed}/{len(self.steps)} |",
            "",
            "## Steps",
            "",
            "| # | Step | Status | Details |",
            "|---|------|--------|---------|",
        ]
        for i, s in enumerate(self.steps, 1):
            status = "✅" if s.passed else "❌"
            detail = s.details if s.passed else s.error
            lines.append(f"| {i} | {s.name} | {status} | {detail[:90]} |")
        failures = [s for s in self.steps if not s.passed]
        if failures:
            lines += ["", "## Failures", ""]
            for s in failures:
                lines += [f"### {s.name}", "", "```", s.error, "```", ""]
        lines += ["", "---", "*Generated by `integration_walkthrough_for_memory.py`*"]
        return "\n".join(lines)


def find_alf_binary() -> Optional[str]:
    on_path = shutil.which("alf")
    if on_path:
        return on_path
    here = Path(__file__).resolve().parent.parent
    for variant in ("release", "debug"):
        cand = here / "target" / variant / "alf"
        if cand.is_file() and os.access(cand, os.X_OK):
            return str(cand)
    return None


# ---------------------------------------------------------------------------
# The source-handler table, as data (mirror of SOURCE_HANDLERS in
# adapter-openclaw/src/memory_parser.rs — keep these in sync).
# ---------------------------------------------------------------------------

HANDLER_TABLE = [
    # (path pattern, memory_type, namespace, chunking)
    ("MEMORY.md", "semantic", "curated", "SplitByHeading(## , fence-aware)"),
    ("memory/YYYY-MM-DD.md  (daily)", "episodic", "daily", "SplitByHeading(## , fence-aware)"),
    ("memory/procedures/*.md", "procedural", "procedural", "OneRecordPerFile"),
    ("memory/curated/*.md", "semantic", "curated", "OneRecordPerFile"),
    ("memory/active-context.md", "summary", "active-context", "OneRecordPerFile"),
    ("memory/gating-policies.md  (legacy)", "procedural", "procedural", "SplitByHeading(## , fence-aware)"),
    ("memory/project-*.md  (legacy)", "semantic", "project", "SplitByHeading(## , fence-aware)"),
    ("memory/*.md  (catch-all)", "semantic", "workspace", "OneRecordPerFile"),
    ("memory/*.txt  (non-Markdown)", "—", "—", "skipped — no structured record"),
]


# ---------------------------------------------------------------------------
# Demo workspace files. Each is chosen to show one handler/strategy clearly.
# ---------------------------------------------------------------------------

# Identity layer (not memory) — present so the export is a realistic agent.
SOUL_MD = "# Atlas\n\nA careful, curious agent.\n"
IDENTITY_MD = "# Identity\n\nRuntime: openclaw.\n"

DAILY_MD = """\
# Saturday, May 23rd, 2026

## 09:05 AM - Reddit Watchdog Recovery

- Status: Manual recovery successful.
- Searched r/LLMDevs and r/aiagents for hot topics.

## 11:30 AM - Telegram digest

Posted the daily digest. The template I pasted was:

```
## Digest YYYY-MM-DD
- highlights
```

Mood: attentive.
"""

PROCEDURE_MD = """\
# Morning Standup Procedure

## Trigger
Cron at 09:00 local time.

## Steps
1. Pull overnight alerts.
2. Post the summary to the team channel.

## Template
```
## Standup YYYY-MM-DD
- Alerts: <count>
```

## Notes
Keep it under five minutes.
"""

CURATED_MD = """\
# Postgres Row-Level Security

## What it is
RLS restricts which rows a role can see, enforced by the database.

## Gotcha
Set the tenant inside the transaction, or policies silently return zero rows.
"""

ACTIVE_CONTEXT_MD = """\
# Current Focus

Shipping the WP2 chunking fix.

## Next
Re-sync the test agents from the fixed adapter.
"""

PROJECT_MD = """\
# Project: Clawsmith

## Status
Beta; daily syncs are green.

## Risks
Schema drift between the adapter and the service.
"""

GATING_MD = """\
# Gating Policies

## Policy: spend
Require human approval for any spend over $100.
"""

NOTES_MD = """\
# Random notes

Free-form thoughts with no real structure.

## A heading
Under the catch-all this stays inside one record, not its own fragment.
"""

MEMORY_MD = """\
## Project architecture
Modular crates: alf-core, alf-cli, adapter-openclaw.

## Team conventions
JSON-first CLI output; progress to stderr.
"""

SCRATCH_TXT = "just a scratch file, not markdown\n"

# Per-file teaching expectations. `records`/`mtype`/`ns` are what WP2 should
# produce; `whole_file_old` marks the only file the PRE-WP2 splitter special-cased.
DEMO = [
    {
        "path": "memory/2026-05-23.md", "content": DAILY_MD,
        "records": 2, "mtype": "episodic", "ns": "daily", "whole_file_old": False,
        "note": "Daily journal: H1 date header dropped, fenced `## Digest` NOT split → one record per real entry.",
    },
    {
        "path": "memory/procedures/morning-standup.md", "content": PROCEDURE_MD,
        "records": 1, "mtype": "procedural", "ns": "procedural", "whole_file_old": False,
        "note": "Procedure: OneRecordPerFile → a single coherent record (used to shred into many).",
    },
    {
        "path": "memory/curated/postgres-rls.md", "content": CURATED_MD,
        "records": 1, "mtype": "semantic", "ns": "curated", "whole_file_old": False,
        "note": "Curated knowledge: OneRecordPerFile.",
    },
    {
        "path": "memory/active-context.md", "content": ACTIVE_CONTEXT_MD,
        "records": 1, "mtype": "summary", "ns": "active-context", "whole_file_old": True,
        "note": "Working memory: one rolling summary record (already whole-file before WP2).",
    },
    {
        "path": "memory/project-clawsmith.md", "content": PROJECT_MD,
        "records": 2, "mtype": "semantic", "ns": "project", "whole_file_old": False,
        "note": "Legacy project file: still SplitByHeading; H1 title dropped.",
    },
    {
        "path": "memory/gating-policies.md", "content": GATING_MD,
        "records": 1, "mtype": "procedural", "ns": "procedural", "whole_file_old": False,
        "note": "Legacy procedural file: classification preserved.",
    },
    {
        "path": "memory/notes.md", "content": NOTES_MD,
        "records": 1, "mtype": "semantic", "ns": "workspace", "whole_file_old": False,
        "note": "Catch-all: any other memory/*.md is one semantic record.",
    },
    {
        "path": "MEMORY.md", "content": MEMORY_MD,
        "records": 2, "mtype": "semantic", "ns": "curated", "whole_file_old": False,
        "note": "Root curated file: one record per topic.",
    },
    {
        "path": "memory/scratch.txt", "content": SCRATCH_TXT,
        "records": 0, "mtype": None, "ns": None, "whole_file_old": False,
        "note": "Non-Markdown: skipped by the parser (still backed up in raw/ via `alf add`).",
    },
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _alf_env(home: Path) -> dict:
    """Child env with HOME redirected to an isolated dir and JSON stdout forced,
    so the demo never touches the host's ~/.alf and parses cleanly."""
    env = dict(os.environ)
    env["HOME"] = str(home)
    env.pop("ALF_HUMAN", None)
    return env


def _read_memory_records(alf_path: Path) -> list[dict]:
    """Pull every memory record out of a local .alf (a ZIP of `memory/*.jsonl`)."""
    recs: list[dict] = []
    with zipfile.ZipFile(alf_path) as z:
        for name in z.namelist():
            if name.startswith("memory/") and name.endswith(".jsonl"):
                for line in z.read(name).decode().splitlines():
                    if line.strip():
                        recs.append(json.loads(line))
    return recs


def naive_old_chunk_count(content: str, whole_file: bool) -> int:
    """Reproduce the PRE-WP2 splitter for contrast: split on every line starting
    with '## ' (NOT fence-aware), keeping a section whenever its full text —
    heading line included — is non-empty. Back then active-context was the only
    whole-file special case, and an H1-only preamble counted as a record."""
    if whole_file:
        return 1 if content.strip() else 0
    sections, cur = [], []
    for line in content.splitlines():
        if line.startswith("## "):
            if cur and "\n".join(cur).strip():
                sections.append(cur)
            cur = [line]
        else:
            cur.append(line)
    if cur and "\n".join(cur).strip():
        sections.append(cur)
    return len(sections)


def _seed_workspace(ws: Path) -> None:
    (ws / "memory" / "procedures").mkdir(parents=True, exist_ok=True)
    (ws / "memory" / "curated").mkdir(parents=True, exist_ok=True)
    (ws / "SOUL.md").write_text(SOUL_MD, encoding="utf-8")
    (ws / "IDENTITY.md").write_text(IDENTITY_MD, encoding="utf-8")
    for f in DEMO:
        (ws / f["path"]).write_text(f["content"], encoding="utf-8")


def _print_tree(ws: Path) -> None:
    print(f"  {c('yellow', 'Demo workspace')}")
    print(f"    {ws.name}/")
    entries = sorted(ws.rglob("*"), key=lambda p: p.relative_to(ws).as_posix())
    for p in entries:
        rel = p.relative_to(ws).as_posix()
        depth = rel.count("/")
        indent = "    " + "  " * depth
        name = p.name + ("/" if p.is_dir() else "")
        print(f"{indent}{c('dim', name)}")
    print()


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------


def step_concept_table(interactive: bool, report: Report) -> None:
    section(1, "The source-handler table (concept)")
    explain(
        """
        Translating a workspace into ALF is a per-file decision. Instead of one
        blind heuristic, each known location declares how it maps. The OpenClaw
        table (adapter-openclaw/src/memory_parser.rs), first match wins:
        """
    )
    w = max(len(r[0]) for r in HANDLER_TABLE)
    print(f"    {c('bold', 'path'.ljust(w))}   {c('bold', 'memory_type'.ljust(10))} {c('bold', 'namespace'.ljust(14))} chunking")
    for pat, mt, ns, ch in HANDLER_TABLE:
        print(f"    {pat.ljust(w)}   {c('cyan', mt.ljust(10))} {c('yellow', ns.ljust(14))} {ch}")
    print()
    report.add(StepResult("Handler table (concept)", True, f"{len(HANDLER_TABLE)} rows"))
    pause(interactive)


def step_concept_chunking(interactive: bool, report: Report) -> None:
    section(2, "Two chunking strategies (concept)")
    explain(
        """
        OneRecordPerFile — the whole file becomes one record. Used for self-
        contained docs: procedures, curated knowledge, active-context. This is
        the fix for "a procedure shredded into 5–7 fragments".

        SplitByHeading { fence_aware, level } — one record per `## ` heading.
        Used for daily journals and MEMORY.md. Two refinements added in WP2:
          • fence-aware: a `## ` line inside a ``` code block is NOT a split.
          • empty-body drop: a section whose body (content minus its heading
            line) is blank is not emitted — this also drops a leading H1 date
            header, the cause of the spurious "Saturday, May 23rd, 2026" record.

        Round-trip is never at risk: the exact bytes live in raw/openclaw/, so
        what's dropped here only affects the structured, indexed view.
        """
    )
    report.add(StepResult("Chunking strategies (concept)", True, "OneRecordPerFile / SplitByHeading"))
    pause(interactive)


def step_export_and_illustrate(interactive: bool, report: Report) -> None:
    section(3, "Run the real `alf export` and inspect the records")
    explain(
        """
        We seed a demo workspace with one file per behavior, run the actual `alf
        export` binary (HOME isolated, no service), then read the .alf and show
        per file: records produced, type/namespace, and — for contrast — what the
        old structure-blind splitter would have emitted.
        """
    )

    alf = find_alf_binary()
    if not alf:
        ok("`alf` not found on PATH or under target/ — skipping (build with `cargo build`)")
        report.add(StepResult("Export + illustrate", True, "alf not available — skipped"))
        pause(interactive)
        return
    print(f"  Using alf binary: {c('dim', alf)}\n")

    passed = True
    failures: list[str] = []
    try:
        with tempfile.TemporaryDirectory() as home_s, tempfile.TemporaryDirectory() as ws_s:
            home, ws = Path(home_s), Path(ws_s) / "workspace"
            ws.mkdir(parents=True)
            _seed_workspace(ws)
            _print_tree(ws)

            alf_path = Path(ws_s) / "demo.alf"
            proc = subprocess.run(
                [alf, "export", "-r", "openclaw", "-w", str(ws), "-o", str(alf_path)],
                capture_output=True, text=True, env=_alf_env(home), timeout=120,
            )
            if proc.returncode != 0:
                raise RuntimeError(f"alf export failed: {(proc.stderr or proc.stdout)[:300]}")
            summary = json.loads(proc.stdout.strip())
            ok(f"alf export → {summary.get('memory_records')} memory records total\n")

            records = _read_memory_records(alf_path)
            by_file: dict[str, list[dict]] = {}
            for r in records:
                origin = (r.get("source") or {}).get("origin_file")
                by_file.setdefault(origin, []).append(r)

            # Per-file illustration + assertions.
            header = f"    {'file'.ljust(38)} {'old→new'.ljust(9)} {'type'.ljust(10)} namespace"
            print(c("bold", header))
            for f in DEMO:
                got = by_file.get(f["path"], [])
                n_new = len(got)
                # Non-.md files were skipped by the walker before WP2 too, so they
                # never reached the splitter — their honest old count is 0.
                is_md = f["path"].endswith(".md")
                n_old = naive_old_chunk_count(f["content"], f["whole_file_old"]) if is_md else 0
                got_type = got[0]["memory_type"] if got else "—"
                got_ns = got[0]["namespace"] if got else "—"
                arrow = f"{n_old}→{n_new}"
                color = "green" if n_new != n_old else "dim"
                print(f"    {f['path'].ljust(38)} {c(color, arrow.ljust(9))} {c('cyan', got_type.ljust(10))} {c('yellow', got_ns)}")
                print(f"      {c('dim', f['note'])}")
                for r in got:
                    first = r["content"].splitlines()[0] if r["content"].strip() else "(empty)"
                    print(f"        {c('dim', '•')} {first[:72]}")

                # Assertions (this doubles as a functional test).
                if n_new != f["records"]:
                    failures.append(f"{f['path']}: expected {f['records']} records, got {n_new}")
                if got:
                    if got_type != f["mtype"]:
                        failures.append(f"{f['path']}: type {got_type} != {f['mtype']}")
                    if got_ns != f["ns"]:
                        failures.append(f"{f['path']}: namespace {got_ns} != {f['ns']}")
            print()

            # Two headline behaviors, called out explicitly.
            daily = by_file.get("memory/2026-05-23.md", [])
            if any(r["content"].strip() == "# Saturday, May 23rd, 2026" for r in daily):
                failures.append("daily: H1 date header leaked as its own record")
            else:
                ok("Screenshot bug fixed: no standalone '# Saturday, May 23rd, 2026' record")
            if any("## Digest YYYY-MM-DD" in r["content"] for r in daily):
                ok("Fence-aware: the `## Digest` line inside ``` stayed inside its entry, no extra split")
            else:
                failures.append("daily: fenced `## Digest` line was not preserved inside a record")
            proc_recs = by_file.get("memory/procedures/morning-standup.md", [])
            if len(proc_recs) == 1 and proc_recs[0]["content"] == PROCEDURE_MD:
                ok("Procedure collapsed to ONE verbatim record (was 5–7 fragments)")
            else:
                failures.append("procedure: not a single verbatim record")
            if "memory/scratch.txt" not in by_file:
                ok("Non-Markdown scratch.txt produced no structured record (raw-only)")
            else:
                failures.append("scratch.txt unexpectedly produced a memory record")

    except (RuntimeError, AssertionError, KeyError, json.JSONDecodeError) as e:
        passed = False
        fail(str(e))

    if failures:
        passed = False
        for f in failures:
            fail(f)

    report.add(StepResult(
        "Export + illustrate",
        passed,
        "per-file chunking + type verified" if passed else "",
        "; ".join(failures) if failures else "",
    ))
    pause(interactive)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--no-pause", action="store_true", help="Run without interactive pauses (for CI)")
    parser.add_argument("--report", type=str, default="integration_memory_report.md",
                        help="Output path for the markdown report")
    args = parser.parse_args()
    interactive = not args.no_pause

    report = Report()
    banner("agent-life Memory Types & Chunking Walkthrough (WP2)")
    print(f"  Subject: OpenClaw source-handler table (local export — no service)")
    print(f"  Mode:    {'interactive' if interactive else 'batch'}\n")
    if interactive:
        print(c("dim", "  Builds a demo workspace, runs `alf export`, and shows how each file chunks."))
        pause(interactive, "Press Enter to begin...")

    try:
        step_concept_table(interactive, report)
        step_concept_chunking(interactive, report)
        step_export_and_illustrate(interactive, report)
    except KeyboardInterrupt:
        print(f"\n\n  {c('yellow', 'Interrupted by user.')}")
        report.add(StepResult("Interrupted", False, error="KeyboardInterrupt"))

    banner("Report")
    Path(args.report).write_text(report.to_markdown(), encoding="utf-8")
    print(f"  Report written to: {Path(args.report).resolve()}\n")

    passed = sum(1 for s in report.steps if s.passed)
    total = len(report.steps)
    color = "green" if passed == total else "red"
    print(f"  {c(color, f'{passed}/{total} steps passed')}\n")
    sys.exit(0 if passed == total else 1)


if __name__ == "__main__":
    main()
