#!/usr/bin/env python3
"""
agent-life Vault Integration Walkthrough
=======================================

Teaches new engineers how the zero-knowledge credentials vault fits into the
sync pipeline: what the vault is and where it lives
(`~/.alf/vault/credentials.json` — runtime-neutral, ciphertext only), what a
vault record looks like field by field, what lands **in the cloud** (opaque S3
blob + Postgres metadata only), and how the vault travels inside an `.alf`
snapshot as the Layer 4 `credentials.json`.

Follows the same UX as `integration_walkthrough.py` (banner, steps, pauses,
markdown report).

Prerequisites:
  pip install requests psycopg2-binary boto3 python-dotenv

Environment (.env or exported): same as integration_walkthrough.py
  API_BASE_URL, API_KEY, NEON_DATABASE_URL, S3_BUCKET_NAME, AWS_REGION

Usage:
  python3 integration_walkthrough_for_vault.py
  python3 integration_walkthrough_for_vault.py --no-pause
  python3 integration_walkthrough_for_vault.py --report vault_report.md
"""

from __future__ import annotations

import argparse
import base64
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
import time
import uuid
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# Reuse clients, UI, connectivity, and report types from the main walkthrough.
_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

import integration_walkthrough as iw

# ---------------------------------------------------------------------------
# Vault-specific agent (must not collide with integration_walkthrough.py)
# ---------------------------------------------------------------------------

VAULT_AGENT_ID = uuid.UUID("e2e10000-feed-4000-b000-000000000002")
VAULT_AGENT_NAME = "E2E Vault Walkthrough Agent"


def _adapt_report_markdown(md: str) -> str:
    return md.replace(
        "agent-life Integration Test Report",
        "agent-life Vault Walkthrough Report",
    ).replace(
        "*Generated by `integration_walkthrough.py`*",
        "*Generated by `integration_walkthrough_for_vault.py`*",
    )


def make_vault_memory(record_id: str, content: str, namespace: str = "default") -> dict:
    return {
        "id": record_id,
        "agent_id": str(VAULT_AGENT_ID),
        "content": content,
        "memory_type": "semantic",
        "source": {"runtime": iw.SOURCE_RUNTIME},
        "temporal": {"created_at": datetime.now(timezone.utc).isoformat()},
        "status": "active",
        "namespace": namespace,
    }


def build_vault_credentials_document(agent_id_str: str) -> dict:
    """Two realistic `alf vault add` records — an email account and a Telegram account.

    The shapes match exactly what `alf vault add` writes into
    `~/.alf/vault/credentials.json`: real-looking AEAD ciphertext, plaintext
    descriptors (service / label / description / tags), and the `alf-vault` tag
    every agent-added record carries.
    """
    now = datetime.now(timezone.utc).isoformat()

    def record(rec_id: str, service: str, label: str, description: str) -> dict:
        return {
            "id": rec_id,
            "agent_id": agent_id_str,
            "service": service,
            "credential_type": "account",
            # Random bytes stand in for a real AEAD blob — without the vault key
            # this is indistinguishable from the secret it protects.
            "encrypted_payload": base64.standard_b64encode(os.urandom(48)).decode("ascii"),
            "encryption": {
                "algorithm": "xchacha20-poly1305",
                "nonce": base64.standard_b64encode(os.urandom(24)).decode("ascii"),
            },
            "created_at": now,
            "label": label,
            "description": description,
            "capabilities_granted": [],
            "tags": ["agent-provisioned", "alf-vault"],
        }

    return {
        "credentials": [
            record(
                "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaa0001",
                "email",
                "kleo@agent-life.run",
                "Agent email account — plaintext metadata, operator-visible.",
            ),
            record(
                "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbb0002",
                "telegram",
                "kleo_bot",
                "Agent Telegram bot account.",
            ),
        ],
        "extra": {},
    }


def build_vault_snapshot_zip(agent_id_str: str) -> bytes:
    """Minimal `.alf` with memory + Layer 4 credentials (same shape the CLI exports)."""
    memories = [
        make_vault_memory(
            "00000000-0000-0000-0000-00000000aa01",
            "Vault walkthrough: memory partitions and credentials layers ship in one archive.",
            "curated",
        ),
    ]
    cred_doc = build_vault_credentials_document(agent_id_str)
    cred_count = len(cred_doc["credentials"])

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        manifest = {
            "alf_version": "1.0.0",
            "created_at": datetime.now(timezone.utc).isoformat(),
            "agent": {
                "id": agent_id_str,
                "name": VAULT_AGENT_NAME,
                "source_runtime": iw.SOURCE_RUNTIME,
            },
            "layers": {
                "memory": {
                    "record_count": len(memories),
                    "index_file": "memory/index.json",
                    "partitions": [
                        {
                            "file": "memory/2026-Q1.jsonl",
                            "from": "2026-01-01",
                            "to": "2026-03-31",
                            "record_count": len(memories),
                            "sealed": False,
                        }
                    ],
                },
                "credentials": {
                    "count": cred_count,
                    "file": "credentials.json",
                },
            },
        }
        zf.writestr("manifest.json", json.dumps(manifest, indent=2))
        zf.writestr(
            "memory/index.json",
            json.dumps({"partitions": manifest["layers"]["memory"]["partitions"]}),
        )
        jsonl = "\n".join(json.dumps(m) for m in memories) + "\n"
        zf.writestr("memory/2026-Q1.jsonl", jsonl)
        zf.writestr("credentials.json", json.dumps(cred_doc, indent=2))
        zf.writestr(
            "raw/openclaw/SOUL.md",
            f"# {VAULT_AGENT_NAME}\n\nPedagogical snapshot including Layer 4.\n",
        )
    return buf.getvalue()


def redact_credentials_for_display(cred_doc: dict) -> dict:
    """Shorten base64 fields for terminal / report output."""

    def short_b64(s: str, keep: int = 28) -> str:
        if len(s) <= keep:
            return s
        return s[:keep] + "…"

    out = json.loads(json.dumps(cred_doc))
    for c in out.get("credentials", []):
        if "encrypted_payload" in c:
            c["encrypted_payload"] = short_b64(c["encrypted_payload"], 32)
        enc = c.get("encryption") or {}
        if enc.get("nonce"):
            enc["nonce"] = short_b64(enc["nonce"], 24)
        c["encryption"] = enc
    return out


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------


def step_vault_zero_knowledge(cfg: iw.Config, report: iw.Report):
    iw.section(1, "Zero-Knowledge Boundary (Concept)")
    iw.explain(
        """
        The **vault** is a local file — `~/.alf/vault/credentials.json` — holding
        Layer 4 credentials **client-encrypted** before they ever reach the API.
        The agent fills it explicitly with `alf vault add`; ALF never scrapes a
        runtime's own keystore.

        • **Vault key** — raw bytes (file or env) or a passphrase stretched with
          Argon2id. The sync service never receives it.
        • **Plaintext secrets** — only on the machine that knows the vault key.
        • **Ciphertext + IV/nonce** — ride inside `credentials.json` in the `.alf`
          ZIP; structurally validated, never decrypted server-side.
        • **Metadata** — fields like `service`, `description`, and `label` are
          plaintext in the blob; operators with DB/S3 access can read them.
          Treat `description` as semi-public unless you use opaque placeholders.

        The cloud stores the **whole archive** in S3 and **indexes** it in Postgres
        (sequence, blob key, sizes). It does not derive or hold vault keys.
        """
    )
    report.add(
        iw.StepResult(
            "ZK boundary (concept)",
            True,
            0,
            "Explains client encryption vs cloud storage",
        )
    )
    iw.pause(cfg)


def step_on_disk_layout(cfg: iw.Config, report: iw.Report):
    iw.section(2, "The Vault On Disk — Location, Neutrality, Anatomy")
    iw.explain(
        """
        The ALF vault is one file:

            ~/.alf/vault/credentials.json

        It is **runtime-neutral** — the same path whether the agent runs on
        OpenClaw or ZeroClaw. It lives under ALF's own home (`~/.alf/`, beside
        `config.toml` and `state/`), NOT inside a runtime directory, and is
        deliberately separate from any runtime keystore (OpenClaw
        `auth-profiles.json`, ZeroClaw `config.toml [secrets]`). ALF never reads
        or syncs those keystores — the agent decides what to vault with
        `alf vault add`.

        It holds a `CredentialsDocument`: a list of independently AEAD-encrypted
        `CredentialRecord`s. Ciphertext only, so syncing it is safe. `alf sync`
        copies it verbatim into the `.alf` archive as the Layer 4
        `credentials.json`; `alf restore` writes it back to the same path.

        Other files on the host (none of which is the vault):
          • `~/.alf/config.toml` — service URL + API key (authenticates you to
            agent-life; unrelated to the vault key).
          • `~/.alf/state/{agent_id}.toml` + `{agent_id}-snapshot.alf` — sync
            cursor + frozen base archive used to compute deltas.
          • **Vault key** — `~/.openclaw/state/.alf-vault-key` (or the zeroclaw
            path), or `ALF_VAULT_KEY`, or a passphrase. Secret; never synced,
            never inside the archive. Needed by `alf vault add` / `decrypt`,
            not by `export` / `sync`.
        """
    )

    # Show what a vault record actually looks like.
    cred_doc = build_vault_credentials_document(str(VAULT_AGENT_ID))
    print(f"  {iw.c('yellow', '~/.alf/vault/credentials.json (redacted)')}:")
    print(json.dumps(redact_credentials_for_display(cred_doc), indent=4))
    print()
    iw.explain(
        """
        A `CredentialRecord`, field by field:
          • `id`                — stable UUID; the selector for `vault delete`.
          • `service` / `label` — plaintext descriptors; how an agent finds a
                                   record without the key. Operator-visible.
          • `credential_type`   — `account`, `api_key`, `oauth_token`, …
          • `encrypted_payload` — base64 AEAD ciphertext. The actual secret
                                   (username + password / token) lives ONLY here.
          • `encryption`        — `algorithm` (xchacha20-poly1305) + `nonce`.
          • `description`       — optional plaintext; treat as semi-public.
          • `tags`              — plaintext; every `alf vault add` record carries
                                   `alf-vault`, the tag that routes it back into
                                   the vault file on `alf restore`.

        Only `encrypted_payload` hides anything. Every other field is readable by
        anyone with the file — by design, so `vault list` / `vault delete` need
        no key.
        """
    )
    report.add(
        iw.StepResult(
            "Vault on disk",
            True,
            0,
            "Location (~/.alf/vault/credentials.json), runtime-neutrality, record anatomy",
        )
    )
    iw.pause(cfg)


def step_create_vault_agent(cfg: iw.Config, api: iw.ApiClient, db: iw.DbClient, report: iw.Report):
    iw.section(3, "Create Agent (Vault Walkthrough ID)")
    iw.explain(
        f"""
        Same as the main walkthrough: `POST /agents` inserts a tenant-scoped row.
        We use a **separate UUID** so this script never collides with
        `integration_walkthrough.py`.

        Agent ID: {VAULT_AGENT_ID}
        """
    )

    t0 = time.time()
    r = api.post_json(
        "/agents",
        {
            "id": str(VAULT_AGENT_ID),
            "name": VAULT_AGENT_NAME,
            "source_runtime": iw.SOURCE_RUNTIME,
        },
    )
    duration = (time.time() - t0) * 1000

    if r.status_code == 201:
        body = r.json()
        iw.ok(f"Agent created (HTTP 201) — sequence {body.get('latest_sequence')}")
        iw.show_data("API response", body)
    elif r.status_code == 409:
        iw.ok("Agent already existed (HTTP 409) — idempotent, continuing")
        body = api.get(f"/agents/{VAULT_AGENT_ID}").json()
    else:
        iw.fail(f"Unexpected status {r.status_code}: {r.text[:200]}")
        report.add(iw.StepResult("Create vault agent", False, duration, error=r.text[:200]))
        return

    row = db.query_one(
        "SELECT id, name, source_runtime, latest_sequence, latest_snapshot_blob "
        "FROM agents WHERE id = %s",
        (str(VAULT_AGENT_ID),),
    )
    if row:
        iw.ok("Agent row found in Neon")
        iw.show_data("DB row", row)
    else:
        iw.fail("Agent row NOT found in Neon")

    report.add(
        iw.StepResult(
            "Create vault agent",
            True,
            duration,
            f"Agent {str(VAULT_AGENT_ID)[:8]}…",
        )
    )
    iw.pause(cfg)


def step_upload_vault_snapshot(
    cfg: iw.Config,
    api: iw.ApiClient,
    db: iw.DbClient,
    s3: iw.S3Client,
    report: iw.Report,
) -> dict:
    iw.section(4, "Upload Snapshot Containing credentials.json")
    iw.explain(
        """
        We build a minimal `.alf` ZIP with:
          • `manifest.json` declaring `layers.credentials` (count + file path)
          • `credentials.json` — pedagogical ciphertext (random bytes) plus a legacy
            `algorithm: "none"` row
          • a tiny memory partition (same archive mechanics as production)

        The API stores the bytes verbatim in S3. No server code path decrypts the
        payload — validation is structural (base64, nonce length, etc.).
        """
    )

    snapshot_bytes = build_vault_snapshot_zip(str(VAULT_AGENT_ID))
    print(f"  Snapshot archive: {len(snapshot_bytes):,} bytes (includes Layer 4)")
    print()

    t0 = time.time()
    r = api.put_binary(f"/agents/{VAULT_AGENT_ID}/snapshot", snapshot_bytes)
    duration = (time.time() - t0) * 1000

    if r.status_code != 201:
        iw.fail(f"Snapshot upload failed (HTTP {r.status_code}): {r.text[:200]}")
        report.add(iw.StepResult("Upload vault snapshot", False, duration, error=r.text[:200]))
        return {}

    body = r.json()
    iw.ok(
        f"Snapshot uploaded (HTTP 201) — sequence {body.get('sequence')}, "
        f"{body.get('size_bytes'):,} bytes"
    )
    iw.show_data("API response", body)

    snap_row = db.query_one(
        "SELECT id, sequence, blob_key, size_bytes FROM snapshots WHERE agent_id = %s "
        "ORDER BY created_at DESC LIMIT 1",
        (str(VAULT_AGENT_ID),),
    )
    if snap_row:
        iw.ok("Snapshot row found in Neon")
        iw.show_data("DB snapshot row", snap_row)

    iw.explain(
        """
        **In-cloud presentation (metadata):** Postgres stores blob pointers and
        numeric metadata — not vault keys, not decrypted secrets. The sensitive
        material exists only inside the object referenced by `blob_key`.
        """
    )

    blob_key = body.get("blob_key", snap_row.get("blob_key", "") if snap_row else "")
    if blob_key:
        exists = s3.object_exists(blob_key)
        if exists:
            head = s3.head_object(blob_key)
            iw.ok(f"S3 object exists — {head['ContentLength']:,} bytes")
            iw.show_data(
                "S3 object",
                {
                    "key": blob_key,
                    "size": head["ContentLength"],
                    "last_modified": str(head["LastModified"]),
                },
            )
        else:
            iw.fail(f"S3 object NOT found: {blob_key}")

    report.add(
        iw.StepResult(
            "Upload vault snapshot",
            True,
            duration,
            f"{len(snapshot_bytes):,} bytes",
        )
    )
    iw.pause(cfg)
    return body


def step_inspect_s3_archive(
    cfg: iw.Config,
    s3: iw.S3Client,
    report: iw.Report,
    upload_body: dict,
):
    iw.section(5, "Download S3 Blob — On-Disk Shape Inside the ZIP")
    iw.explain(
        """
        Engineers with object-store access can download the snapshot. Inside, open
        `manifest.json` and `credentials.json`.

        Below we **redact** long base64 strings. Even without redaction, ciphertext
        without the vault key does not reveal the original secret.
        """
    )

    blob_key = upload_body.get("blob_key", "")
    if not blob_key:
        iw.fail("No blob_key from upload response — cannot inspect S3 object")
        report.add(
            iw.StepResult(
                "Inspect S3 archive",
                False,
                0,
                error="missing blob_key",
            )
        )
        return

    t0 = time.time()
    try:
        obj = s3.s3.get_object(Bucket=s3.bucket, Key=blob_key)
        raw = obj["Body"].read()
    except Exception as e:
        duration = (time.time() - t0) * 1000
        iw.fail(f"S3 get_object failed: {e}")
        report.add(iw.StepResult("Inspect S3 archive", False, duration, error=str(e)))
        return
    duration = (time.time() - t0) * 1000

    try:
        zf = zipfile.ZipFile(io.BytesIO(raw))
        names = zf.namelist()
        iw.ok(f"Valid ZIP — {len(names)} entries (showing first 8): {names[:8]}")
        manifest = json.loads(zf.read("manifest.json"))
        cred_raw = zf.read("credentials.json").decode("utf-8")
        cred_doc = json.loads(cred_raw)
    except Exception as e:
        iw.fail(f"Failed to parse archive: {e}")
        report.add(iw.StepResult("Inspect S3 archive", False, duration, error=str(e)))
        return

    iw.show_data(
        "manifest.layers.credentials",
        manifest.get("layers", {}).get("credentials", {}),
    )
    print(f"  {iw.c('yellow', 'credentials.json (redacted)')}:")
    print(json.dumps(redact_credentials_for_display(cred_doc), indent=4))
    print()

    report.add(
        iw.StepResult(
            "Inspect S3 archive",
            True,
            duration,
            f"Downloaded {len(raw):,} bytes",
        )
    )
    iw.pause(cfg)


def step_surgical_delete_concept(cfg: iw.Config, report: iw.Report):
    iw.section(6, "Surgical Delete (`alf vault delete`) — No Key")
    iw.explain(
        """
        The `alf vault` command family: `keygen` mints a key; `add` encrypts a
        credential into `~/.alf/vault/credentials.json`; `list` and `delete`
        work on plaintext descriptors only; `decrypt` reads one secret back.
        `add` and `decrypt` need the vault key — `list` and `delete` do not.

        **`alf vault delete`** removes a credential **record** from the vault file
        using only structural metadata (id / service / label / description match).
        It does **not** need the vault key, because it never decrypts — it edits
        JSON and rewrites the file (or `--out` for a copy).

        Contrast with **`alf vault decrypt`**, which requires the vault key and a TTY
        unless `--yes-insecure`.

        After deletion, the next `alf sync` carries the smaller credential set;
        the cloud still never sees plaintext.
        """
    )
    report.add(
        iw.StepResult(
            "Surgical delete (concept)",
            True,
            0,
            "Explains keyless metadata edit vs decrypt",
        )
    )
    iw.pause(cfg)


def step_optional_alf_vault_list(cfg: iw.Config, report: iw.Report):
    iw.section(7, "Optional — `alf vault list --in` (Local CLI)")
    iw.explain(
        """
        If `alf` is on your PATH, we write a temporary `credentials.json` and run
        `alf vault list --in FILE` to show **non-secret** descriptors the CLI surfaces
        without a vault key.

        Skip silently if `alf` is not installed.
        """
    )

    t0 = time.time()
    alf = shutil.which("alf")
    if not alf:
        iw.ok("`alf` not found on PATH — skipping CLI demo")
        report.add(
            iw.StepResult(
                "alf vault list (optional)",
                True,
                (time.time() - t0) * 1000,
                "alf not on PATH",
            )
        )
        iw.pause(cfg)
        return

    cred_doc = build_vault_credentials_document(str(VAULT_AGENT_ID))
    tmp_path: Optional[str] = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".credentials.json",
            delete=False,
            encoding="utf-8",
        ) as tmp:
            tmp_path = tmp.name
            json.dump(cred_doc, tmp, indent=2)
        proc = subprocess.run(
            [alf, "vault", "list", "--in", tmp_path],
            capture_output=True,
            text=True,
            timeout=60,
        )
    finally:
        if tmp_path:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass

    duration = (time.time() - t0) * 1000
    if proc.returncode == 0:
        iw.ok(f"`alf vault list --in …` ({alf})")
        if proc.stdout:
            print(proc.stdout)
        report.add(
            iw.StepResult(
                "alf vault list (optional)",
                True,
                duration,
                "CLI listed descriptors",
            )
        )
    else:
        iw.fail(f"`alf vault list --in` exited {proc.returncode}")
        err = (proc.stderr or proc.stdout or "")[:300]
        print(err)
        report.add(
            iw.StepResult(
                "alf vault list (optional)",
                False,
                duration,
                error=err,
            )
        )
    iw.pause(cfg)


def step_cleanup_vault_agent(
    cfg: iw.Config,
    api: iw.ApiClient,
    db: iw.DbClient,
    s3: iw.S3Client,
    report: iw.Report,
):
    iw.section(8, "Cleanup — Delete Vault Walkthrough Agent")
    iw.explain(
        """
        `DELETE /agents/:id` removes the agent, cascades snapshot/delta rows, and
        deletes objects under `{tenant_id}/{agent_id}/` in S3 — same as the main
        walkthrough.
        """
    )

    agent_row = db.query_one(
        "SELECT tenant_id FROM agents WHERE id = %s",
        (str(VAULT_AGENT_ID),),
    )
    tenant_id = str(agent_row["tenant_id"]) if agent_row else None
    s3_prefix = f"{tenant_id}/{VAULT_AGENT_ID}/" if tenant_id else None
    objects_before = s3.list_objects(s3_prefix) if s3_prefix else []
    print(f"  S3 objects before delete: {len(objects_before)}")

    t0 = time.time()
    r = api.delete(f"/agents/{VAULT_AGENT_ID}")
    duration = (time.time() - t0) * 1000

    if r.status_code == 200:
        body = r.json()
        iw.ok(f"Agent deleted (HTTP 200) — {body.get('objects_removed', '?')} S3 objects removed")
        iw.show_data("API response", body)
    elif r.status_code == 404:
        iw.ok("Agent already deleted (HTTP 404)")
    else:
        iw.fail(f"Delete failed (HTTP {r.status_code}): {r.text[:200]}")
        report.add(iw.StepResult("Cleanup vault agent", False, duration, error=r.text[:200]))
        return

    agent_row = db.query_one("SELECT id FROM agents WHERE id = %s", (str(VAULT_AGENT_ID),))
    snap_count = db.query_one(
        "SELECT count(*) as n FROM snapshots WHERE agent_id = %s",
        (str(VAULT_AGENT_ID),),
    )
    delta_count = db.query_one(
        "SELECT count(*) as n FROM deltas WHERE agent_id = %s",
        (str(VAULT_AGENT_ID),),
    )

    if not agent_row:
        iw.ok("Agent row deleted from Neon")
    else:
        iw.fail("Agent row still exists!")
    iw.ok(f"Snapshot rows remaining: {snap_count['n'] if snap_count else '?'}")
    iw.ok(f"Delta rows remaining: {delta_count['n'] if delta_count else '?'}")

    if s3_prefix:
        objects_after = s3.list_objects(s3_prefix)
        if len(objects_after) == 0:
            iw.ok("S3 prefix is empty — all blobs removed")
        else:
            iw.fail(f"S3 still has {len(objects_after)} objects under {s3_prefix}")

    report.add(
        iw.StepResult(
            "Cleanup vault agent",
            True,
            duration,
            f"Removed agent + {len(objects_before)} S3 objects",
        )
    )
    iw.pause(cfg)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--no-pause",
        action="store_true",
        help="Run without interactive pauses (for CI)",
    )
    parser.add_argument(
        "--report",
        type=str,
        default="integration_vault_report.md",
        help="Output path for the markdown report",
    )
    args = parser.parse_args()

    cfg = iw.Config.from_env(interactive=not args.no_pause)
    api = iw.ApiClient(cfg)
    db = iw.DbClient(cfg)
    s3 = iw.S3Client(cfg)

    report = iw.Report()
    db_host = cfg.db_url.split("@")[-1].split("/")[0] if "@" in cfg.db_url else "?"
    report.config_summary = {
        "api_url": cfg.api_url,
        "s3_bucket": cfg.s3_bucket,
        "db_host": db_host,
    }

    iw.banner("agent-life Vault Integration Walkthrough")
    print(f"  API:      {cfg.api_url}")
    print(f"  S3:       {cfg.s3_bucket}")
    print(f"  DB:       {db_host}")
    print(f"  Agent ID: {VAULT_AGENT_ID}")
    print(f"  Mode:     {'interactive' if cfg.interactive else 'batch'}")
    print()

    if cfg.interactive:
        print(
            iw.c(
                "dim",
                "  This walkthrough explains the vault and uploads a snapshot with "
                "Layer 4 credentials.",
            )
        )
        print(iw.c("dim", "  Press Enter at each prompt to continue, or Ctrl-C to abort."))
        iw.pause(cfg, "Press Enter to begin...")

    try:
        iw.step_connectivity(cfg, api, db, s3, report)
        step_vault_zero_knowledge(cfg, report)
        step_on_disk_layout(cfg, report)
        step_create_vault_agent(cfg, api, db, report)
        upload_body = step_upload_vault_snapshot(cfg, api, db, s3, report)
        if upload_body:
            step_inspect_s3_archive(cfg, s3, report, upload_body)
        step_surgical_delete_concept(cfg, report)
        step_optional_alf_vault_list(cfg, report)
        step_cleanup_vault_agent(cfg, api, db, s3, report)

    except KeyboardInterrupt:
        print(f"\n\n  {iw.c('yellow', 'Interrupted by user.')}")
        print(f"  {iw.c('yellow', f'Agent {VAULT_AGENT_ID} may need manual cleanup.')}")
        report.add(iw.StepResult("Interrupted", False, 0, error="KeyboardInterrupt"))

    iw.banner("Report")
    md = _adapt_report_markdown(report.to_markdown())
    report_path = Path(args.report)
    report_path.write_text(md, encoding="utf-8")
    print(f"  Report written to: {report_path.resolve()}")
    print()

    passed = sum(1 for s in report.steps if s.passed)
    total = len(report.steps)
    total_ms = sum(s.duration_ms for s in report.steps)
    color = "green" if passed == total else "red"
    print(f"  {iw.c(color, f'{passed}/{total} steps passed')}  ({total_ms:.0f} ms total)")
    print()

    sys.exit(0 if passed == total else 1)


if __name__ == "__main__":
    main()
