#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd -P)
LOCK_FILE="$SCRIPT_DIR/integration-fixture.lock"
ENV_VERIFIER="$SCRIPT_DIR/verify_generator_env.py"

usage() {
    cat <<'USAGE'
Usage: ./scripts/run_integration_tests.sh [options]

Options:
  --schema-dir <checkout>  Use this exact, clean data-format Git checkout.
  --offline                Require --schema-dir; do not use pip or Git remotes.
  --check                  Verify the committed fixture matches regenerated bytes.
  --regenerate-fixture     Show reviewed SHA changes, then atomically update fixtures.
  --generate-only          Generate and validate without invoking Cargo.
  --test-fixture-tools     Run fixture-tooling regressions in the locked generator env.
  -h, --help               Show this help.

The normal command uses a newly-created directory under TMPDIR and removes it on exit.

Interpreter selection: set ALF_INTEGRATION_PYTHON to an exact Python executable when
needed. Otherwise, the runner prefers python<locked-major.minor> (for example,
python3.14) and falls back to python3 only when it has the locked minor version.
USAGE
}

fail() {
    echo "ERROR: $*" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || fail "$1 could not be found."
}

CHECKOUT=""
OFFLINE=0
CHECK=0
REGENERATE=0
GENERATE_ONLY=0
TEST_FIXTURE_TOOLS=0

while (($#)); do
    case "$1" in
        --schema-dir)
            (($# >= 2)) || fail "--schema-dir requires a checkout path."
            CHECKOUT=$2
            shift 2
            ;;
        --offline)
            OFFLINE=1
            shift
            ;;
        --check)
            CHECK=1
            shift
            ;;
        --regenerate-fixture)
            REGENERATE=1
            shift
            ;;
        --generate-only)
            GENERATE_ONLY=1
            shift
            ;;
        --test-fixture-tools)
            TEST_FIXTURE_TOOLS=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            fail "unknown option: $1"
            ;;
    esac
done

(( CHECK && REGENERATE )) && fail "--check and --regenerate-fixture are mutually exclusive."
(( REGENERATE && GENERATE_ONLY )) &&
    fail "--regenerate-fixture cannot be combined with --generate-only."
(( TEST_FIXTURE_TOOLS && GENERATE_ONLY )) &&
    fail "--test-fixture-tools cannot be combined with --generate-only."
(( OFFLINE )) && [[ -z "$CHECKOUT" ]] && fail "--offline requires --schema-dir <checkout>."

require_command git
[[ -f "$LOCK_FILE" ]] || fail "missing integration lock: $LOCK_FILE"
# shellcheck source=/dev/null
source "$LOCK_FILE"

for variable in SCHEMA_REPOSITORY SCHEMA_COMMIT FIXTURE_ALF_FORMAT_VERSION FIXTURE_SEED \
    GENERATOR_PYTHON_MINOR GENERATOR_REQUIREMENTS_LOCK; do
    [[ -n ${!variable:-} ]] || fail "$LOCK_FILE does not define $variable."
done

export PYTHONHASHSEED=0

select_generator_python() {
    local candidate candidate_path actual_python_minor

    if [[ -n ${ALF_INTEGRATION_PYTHON:-} ]]; then
        candidate=$ALF_INTEGRATION_PYTHON
        candidate_path=$(command -v "$candidate") ||
            fail "ALF_INTEGRATION_PYTHON could not be found: $candidate"
        actual_python_minor=$("$candidate_path" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
        [[ "$actual_python_minor" == "$GENERATOR_PYTHON_MINOR" ]] ||
            fail "ALF_INTEGRATION_PYTHON must be Python $GENERATOR_PYTHON_MINOR; $candidate_path is $($candidate_path --version)."
        printf '%s\n' "$candidate_path"
        return
    fi

    for candidate in "python$GENERATOR_PYTHON_MINOR" python3; do
        candidate_path=$(command -v "$candidate" 2>/dev/null) || continue
        actual_python_minor=$("$candidate_path" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
        if [[ "$actual_python_minor" == "$GENERATOR_PYTHON_MINOR" ]]; then
            printf '%s\n' "$candidate_path"
            return
        fi
    done

    fail "fixture generation requires Python $GENERATOR_PYTHON_MINOR; set ALF_INTEGRATION_PYTHON or put python$GENERATOR_PYTHON_MINOR on PATH."
}

PYTHON_BIN=$(select_generator_python)

REQUIREMENTS_LOCK="$REPO_ROOT/$GENERATOR_REQUIREMENTS_LOCK"
[[ -f "$REQUIREMENTS_LOCK" ]] || fail "missing generator requirements lock: $REQUIREMENTS_LOCK"
[[ -f "$ENV_VERIFIER" ]] || fail "missing generator environment verifier: $ENV_VERIFIER"

RUN_DIR=$(mktemp -d "${TMPDIR:-/tmp}/alf-integration.XXXXXX")
ARCHIVE_STAGE=""
REVISION_STAGE=""
cleanup_run_dir() {
    local status=$?
    local stage
    for stage in "$ARCHIVE_STAGE" "$REVISION_STAGE"; do
        if [[ -n "$stage" ]]; then
            rm -f -- "$stage" || echo "WARNING: could not remove staged fixture: $stage" >&2
        fi
    done
    rm -rf -- "$RUN_DIR" || echo "WARNING: could not remove temporary directory: $RUN_DIR" >&2
    return "$status"
}
trap cleanup_run_dir EXIT

OUTPUT_ARCHIVE="$RUN_DIR/synthetic-agent.alf"
OUTPUT_SCHEMA_REVISION="$RUN_DIR/schema_version.txt"
REPORT_DIR="$RUN_DIR/reports"
mkdir -p "$REPORT_DIR"

verify_generator_environment() {
    "$PYTHON_BIN" "$ENV_VERIFIER" \
        --lock "$REQUIREMENTS_LOCK" \
        --python-minor "$GENERATOR_PYTHON_MINOR"
}

if (( OFFLINE )); then
    verify_generator_environment
elif ! verify_generator_environment; then
    # Do not mutate a PEP 668-managed interpreter or a caller's active virtualenv.
    echo "-> Creating isolated generator environment..."
    "$PYTHON_BIN" -m venv "$RUN_DIR/venv"
    PYTHON_BIN="$RUN_DIR/venv/bin/python"
    echo "-> Installing exact generator requirements..."
    "$PYTHON_BIN" -m pip install --require-hashes -r "$REQUIREMENTS_LOCK"
    verify_generator_environment
fi

verify_schema_checkout() {
    local candidate=$1
    local actual_head status

    actual_head=$(git -C "$candidate" rev-parse HEAD 2>/dev/null) ||
        fail "$candidate is not a Git checkout."
    [[ "$actual_head" == "$SCHEMA_COMMIT" ]] ||
        fail "schema checkout is at $actual_head; expected $SCHEMA_COMMIT."

    status=$(git -C "$candidate" status --porcelain --untracked-files=all -- schemas)
    [[ -z "$status" ]] || fail "schema checkout has modified or untracked schema files:
$status"

    [[ -f "$candidate/schemas/manifest.schema.json" ]] ||
        fail "$candidate does not contain schemas/manifest.schema.json."
}


if [[ -n "$CHECKOUT" ]]; then
    CHECKOUT=$(cd -- "$CHECKOUT" && pwd -P)
else
    CHECKOUT="$RUN_DIR/agent-life-data-format"
    echo "-> Fetching pinned schema commit $SCHEMA_COMMIT..."
    git init -q "$CHECKOUT"
    git -C "$CHECKOUT" remote add origin "$SCHEMA_REPOSITORY"
    git -C "$CHECKOUT" fetch -q --depth=1 origin "$SCHEMA_COMMIT"
    git -C "$CHECKOUT" checkout -q --detach FETCH_HEAD
fi

verify_schema_checkout "$CHECKOUT"
printf '%s\n' "$SCHEMA_COMMIT" > "$OUTPUT_SCHEMA_REVISION"

echo "-> Generating deterministic fixture..."
"$PYTHON_BIN" "$SCRIPT_DIR/generate_synthetic_data.py" \
    --schema-dir "$CHECKOUT/schemas" \
    --output "$OUTPUT_ARCHIVE" \
    --alf-version "$FIXTURE_ALF_FORMAT_VERSION" \
    --seed "$FIXTURE_SEED" \
    --schema-revision "$SCHEMA_COMMIT"

archive_sha=$(sha256sum "$OUTPUT_ARCHIVE" | awk '{print $1}')
lock_sha=$(sha256sum "$REQUIREMENTS_LOCK" | awk '{print $1}')
adapter_commit=$(git -C "$REPO_ROOT" rev-parse HEAD)
python_version=$("$PYTHON_BIN" --version)
jsf_version=$("$PYTHON_BIN" "$ENV_VERIFIER" --lock "$REQUIREMENTS_LOCK" \
    --python-minor "$GENERATOR_PYTHON_MINOR" --print-version jsf)
faker_version=$("$PYTHON_BIN" "$ENV_VERIFIER" --lock "$REQUIREMENTS_LOCK" \
    --python-minor "$GENERATOR_PYTHON_MINOR" --print-version faker)

echo "-> Adapter commit: $adapter_commit"
echo "-> Schema commit: $SCHEMA_COMMIT"
echo "-> Python: $python_version"
echo "-> Generator lock SHA-256: $lock_sha"
echo "-> Fixture SHA-256: $archive_sha"
echo "-> Temporary output (removed on exit): $RUN_DIR"

check_fixture() {
    local expected_archive="$REPO_ROOT/alf-cli/fixtures/synthetic-agent.alf"
    local expected_revision="$REPO_ROOT/alf-cli/fixtures/schema_version.txt"
    local stale=0

    for pair in "$OUTPUT_ARCHIVE:$expected_archive" "$OUTPUT_SCHEMA_REVISION:$expected_revision"; do
        local generated=${pair%%:*}
        local tracked=${pair#*:}
        if ! cmp -s "$generated" "$tracked"; then
            echo "STALE: $tracked does not match generated output." >&2
            echo "  generated SHA-256: $(sha256sum "$generated" | awk '{print $1}')" >&2
            echo "  tracked SHA-256:   $(sha256sum "$tracked" | awk '{print $1}')" >&2
            stale=1
        fi
    done
    (( stale == 0 )) || fail "run --regenerate-fixture after reviewing the reported differences."
}

if (( CHECK )); then
    check_fixture
fi

if (( GENERATE_ONLY )); then
    echo "Generated and schema-validated fixture without running Cargo."
    exit 0
fi

echo "-> Running Cargo integration test..."
export ALF_INTEGRATION_FIXTURE="$OUTPUT_ARCHIVE"
export ALF_INTEGRATION_SCHEMA_REVISION="$SCHEMA_COMMIT"
export ALF_INTEGRATION_REPORT_DIR="$REPORT_DIR"
export ALF_INTEGRATION_ADAPTER_COMMIT="$adapter_commit"
export ALF_INTEGRATION_FIXTURE_ALF_VERSION="$FIXTURE_ALF_FORMAT_VERSION"
export ALF_INTEGRATION_FIXTURE_SHA256="$archive_sha"
export ALF_INTEGRATION_PYTHON_VERSION="$python_version"
export ALF_INTEGRATION_REQUIREMENTS_LOCK_SHA256="$lock_sha"
export ALF_INTEGRATION_JSF_VERSION="$jsf_version"
export ALF_INTEGRATION_FAKER_VERSION="$faker_version"

cargo test --locked -p alf-cli --test integration_tests

if (( REGENERATE )); then
    fixture_dir="$REPO_ROOT/alf-cli/fixtures"
    tracked_archive="$fixture_dir/synthetic-agent.alf"
    tracked_revision="$fixture_dir/schema_version.txt"
    echo "-> Reviewed fixture update:"
    for pair in "$OUTPUT_ARCHIVE:$tracked_archive" "$OUTPUT_SCHEMA_REVISION:$tracked_revision"; do
        generated=${pair%%:*}
        tracked=${pair#*:}
        echo "  $tracked"
        echo "    old SHA-256: $(sha256sum "$tracked" | awk '{print $1}')"
        echo "    new SHA-256: $(sha256sum "$generated" | awk '{print $1}')"
    done
    ARCHIVE_STAGE=$(mktemp "$fixture_dir/.synthetic-agent.alf.XXXXXX")
    REVISION_STAGE=$(mktemp "$fixture_dir/.schema_version.txt.XXXXXX")
    cp "$OUTPUT_ARCHIVE" "$ARCHIVE_STAGE"
    cp "$OUTPUT_SCHEMA_REVISION" "$REVISION_STAGE"
    chmod 0644 "$ARCHIVE_STAGE" "$REVISION_STAGE"
    mv -f "$ARCHIVE_STAGE" "$tracked_archive"
    ARCHIVE_STAGE=""
    mv -f "$REVISION_STAGE" "$tracked_revision"
    REVISION_STAGE=""
fi

if (( TEST_FIXTURE_TOOLS )); then
    echo "-> Running fixture tooling regressions..."
    ALF_INTEGRATION_PYTHON="$PYTHON_BIN" "$PYTHON_BIN" -m unittest "$SCRIPT_DIR/test_integration_fixture_tools.py"
fi

echo "=================================================="
echo " Integration Tests Completed Successfully!"
echo " Temporary report cleaned up with $RUN_DIR"
echo "=================================================="
